version: '3'
services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123
      - MYSQL_USER=fampay
      - MYSQL_PASSWORD=mysql123
      - MYSQL_DATABASE=fampay_youtube
    volumes:
      - ./database/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql:ro
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]

  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DBAddr=db:3306
      - DBUser=fampay
      - DBPass=mysql123
      - DBName=fampay_youtube
      - APIKeys=AIzaSyBpacQLDJKaclSr9iKrjTuuGjMpiXCIaZI
      - YoutubeCron="@every 10m"
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy